- name: setting up catalogue component 
  hosts: catalogue 
  become: yes 
  tasks: 
  - name: disabling current version of nodejs 
    ansible.builtin.command: "dnf module disable nodejs -y" 
    register: disable_output 

  - name: print output 
    ansible.builtin.debug: 
      msg: "{{ disable_output }}" 

  - name: enabling required version of nodejs 
    ansible.builtin.command: "dnf module enable nodejs:20 -y" 
    register: enable_output 

  - name: print ouput 
    ansible.builtin.debug:
      msg: "{{ enable_output }}" 

  - name: Install nodejs package 
    ansible.builtin.package:
      name: nodejs
      state: present 

  - name: creating system user 
    ansible.builtin.user: 
      name: roboshop 
      home: /app 
      system: true 
      shell: /sbin/nologin 

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /app
      state: directory 

  - name: Download application code as zip file 
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /tmp/catalogue.zip 

  - name: unzipping application code 
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app 
      remote_src: yes  

  - name: Install packages or dependencies 
    community.general.npm:
      path: /app   

  - name: copy catalogue.service file 
    ansible.builtin.copy: 
      src: catalogue.service 
      dest: /etc/systemd/system/catalogue.service                  

