- name: configuring catalogue application 
  hosts: catalogue 
  become: yes 
  tasks: 
  - name: disabling nodejs 
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: enabling nodejs required version 
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: install package 
    ansible.builtin.package: 
      name: nodejs 
      state: present 

  - name: create system user 
    ansible.builtin.user:
      name: roboshop 
      shell: /sbin/nologin 
      system: true 
      home: /app 

  - name: creating a directory 
    ansible.builtin.file: 
      path: /app 
      state: directory     

  - name: download the application code 
    ansible.builtin.get_url: 
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip 

  - name: unzipping a file that is already in remote machine 
    ansible.builtin.unarchive: 
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes 

  - name: installing libraries 
    community.general.npm: 
      path: /app 
          
    

