- name: setting up catalogue component 
  hosts: catalogue 
  become: yes 
  tasks: 
  - name: disabling current version of nodejs 
    ansible.builtin.command: "dnf module disable nodejs -y" 
    register: disable_output 

  - name: print output 
    ansible.builtin.debug: 
      msg: "{{ disable_output }}" 

  - name: enabling required version of nodejs 
    ansible.builtin.command: "dnf module enable nodejs:20 -y" 
    register: enable_output 

  - name: print ouput 
    ansible.builtin.debug:
      msg: "{{ enable_output }}" 

  - name: Install nodejs package 
    ansible.builtin.package:
      name: nodejs
      state: present 

  - name: creating system user 
    ansible.builtin.user: 
      name: roboshop 
      home: /app 
      system: true 
      shell: /sbin/nologin     

