- name: setting up mongodb 
  hosts: mongodb 
  become: yes 
  tasks: 
  - name: copying file to a remote server 
    ansible.builtin.copy: 
      src: mongo.repo 
      dest: /etc/yum.repos.d/mongo.repo 