- name: configuring payment component 
  hosts: payment 
  become: yes 
  tasks: 
  - name: installing python packages 
    ansible.builtin.package: 
      name: "{{ item }}" 
      state: present 
    loop:
    - python3 
    - gcc 
    - python3-devel  