- name: configuring rabbitmq 
  hosts: rabbitmq 
  become: yes 
  tasks: 
  - name: copy rabbitmq.repo to remote server 
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo 

  - name: install rabbitmq-server 
    ansible.builtin.package: 
      name: rabbitmq-server 
      state: present 

  - name: start and enable rabbitmq service 
    ansible.builtin.service: 
      name: rabbitmq-server 
      state: started 
      enabled: yes 

  - name: adding user 
    ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123 

  - name: setting permissions 
    ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*" 
                   