- name: setting up redis component 
  hosts: redis 
  become: yes 
  tasks: 
  - name: diabling default redis version 
    ansible.builtin.command: dnf module disable redis -y 
    register: disable_output 

  - name: print output 
    ansible.builtin.debug: 
      msg: "{{ disable_output }}"   

  - name: enabling required redis version 
    ansible.builtin.command: dnf module enable redis:7 -y 
    register: enable_output 

  - name: print output 
    ansible.builtin.debug: 
      msg: "{{ enable_output }}"     