- name: setting up redis component 
  hosts: redis 
  become: yes 
  tasks: 
  - name: diabling default redis version 
    ansible.builtin.command: dnf module disable redis -y 
  #   register: disable_output 

  # - name: print output 
  #   ansible.builtin.debug: 
  #     msg: "{{ disable_output }}"   

  - name: enabling required redis version 
    ansible.builtin.command: dnf module enable redis:7 -y 
  #   register: enable_output 

  # - name: print output 
  #   ansible.builtin.debug: 
  #     msg: "{{ enable_output }}" 

  - name: install redis  
    ansible.builtin.package: 
      name: redis 
      state: present 

  - name: Replace text in a File
    ansible.builtin.replace: 
      path: /etc/redis/redis.conf 
      regexp: '127.0.0.1'
      replace: '0.0.0.0' 

  - name: allow remote connections 
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'protected-mode'
      line: protected-mode no 

  - name: start and enable redis service 
    ansible.builtin.service: 
      name: redis 
      state: started 
      enabled: yes               