- name: configuring user component 
  hosts: user 
  become: yes 
  tasks:
  - name: disabling nodejs module 
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: enabling required nodejs module 
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: install nodejs 
    ansible.builtin.package:
      name: nodejs 
      state: present 